_format_version: "3.0"
consumers:
- keyauth_credentials:
  - key: ${{ env "DECK_KONG_KEY_AUTH" }}
  username: kong-api-gateway
plugins:
- config:
    allow: []
    deny:
    - Assetnote
    - python-httpx
    - CMS-Checker
    - BadBot/1.0
    - .*Scrapy.*
  enabled: true
  name: bot-detection
  protocols:
  - grpc
  - grpcs
  - http
  - https
- config:
    echo_downstream: true
    generator: uuid#counter
    header_name: request-id
  enabled: true
  name: correlation-id
  protocols:
  - grpc
  - grpcs
  - http
  - https
- config:
    content_type: application/json
    custom_fields_by_lua: null
    flush_timeout: 2
    headers:
      Authorization: Bearer ${{ env "DECK_LOG_BEARER_TOKEN" }}
    http_endpoint: ${{ env "DECK_LOG_URL" }}
    keepalive: 60000
    method: POST
    queue:
      initial_retry_delay: 0.01
      max_batch_size: 1
      max_bytes: null
      max_coalescing_delay: 1
      max_entries: 10000
      max_retry_delay: 60
      max_retry_time: 60
    queue_size: 10
    retry_count: 10
    timeout: 1000
  enabled: true
  name: http-log
  protocols:
  - grpc
  - grpcs
  - http
  - https
- config:
    day: null
    error_code: 429
    error_message: API rate limit exceeded
    fault_tolerant: true
    header_name: null
    hide_client_headers: false
    hour: null
    limit_by: consumer
    minute: 100
    month: null
    path: null
    policy: local
    redis_database: 0
    redis_host: null
    redis_password: null
    redis_port: 6379
    redis_server_name: null
    redis_ssl: false
    redis_ssl_verify: false
    redis_timeout: 2000
    redis_username: null
    second: null
    sync_rate: -1
    year: null
  enabled: true
  name: rate-limiting
  protocols:
  - grpc
  - grpcs
  - http
  - https
- config:
    allowed_payload_size: 10
    require_content_length: false
    size_unit: megabytes
  enabled: true
  name: request-size-limiting
  protocols:
  - grpc
  - grpcs
  - http
  - https
routes:
- https_redirect_status_code: 426
  name: block-favicon
  path_handling: v0
  paths:
  - /favicon.ico
  plugins:
  - config:
      body: null
      content_type: null
      echo: false
      message: No favicon
      status_code: 200
      trigger: null
    enabled: true
    name: request-termination
    protocols:
    - grpc
    - grpcs
    - http
    - https
  preserve_host: false
  protocols:
  - http
  - https
  regex_priority: 0
  request_buffering: true
  response_buffering: true
  strip_path: true
services:
- connect_timeout: 60000
  enabled: true
  host: httpbin-upstream
  name: httpbin
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: httpbin_route
    path_handling: v0
    paths:
    - /api/httpbin
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: localhost
  name: kong-api-gateway
  plugins:
  - config:
      anonymous: null
      hide_credentials: false
      key_in_body: false
      key_in_header: true
      key_in_query: true
      key_names:
      - apikey
      run_on_preflight: true
    enabled: true
    name: key-auth
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 8001
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    id: 187a9376-e1a4-4a39-b446-b8d51f673dd6
    path_handling: v0
    paths:
    - /kong-api-gateway
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: ${{ env "DECK_SUPABASE_HOST" }}
  name: supabase-auth-service
  path: /auth/v1
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: supabase-auth-route
    path_handling: v0
    paths:
    - /api/auth
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
upstreams:
- algorithm: round-robin
  hash_fallback: none
  hash_on: none
  hash_on_cookie_path: /
  healthchecks:
    active:
      concurrency: 10
      healthy:
        http_statuses:
        - 200
        - 302
        interval: 0
        successes: 0
      http_path: /
      https_verify_certificate: true
      timeout: 1
      type: http
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        - 404
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
        interval: 0
        tcp_failures: 0
        timeouts: 0
    passive:
      healthy:
        http_statuses:
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 226
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 306
        - 307
        - 308
        successes: 0
      type: http
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        - 500
        - 503
        tcp_failures: 0
        timeouts: 0
    threshold: 0
  name: httpbin-upstream
  slots: 10000
  targets:
  - target: httpbin.org:80
    weight: 1
  use_srv_name: false
